# Generated by Django 3.0.3 on 2020-07-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
